[package]
name = "vaults"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.6", features = ["gettext-system"] }
gtk-macros = "0.2"
once_cell = "1.5"
quick-error = "2.0.0"
strum = "0.20"
strum_macros = "0.20"
toml = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
proc-mounts = "0.2"

[dependencies.gtk]
package = "gtk4"
git = "https://github.com/gtk-rs/gtk4-rs"

[dependencies.adw]
git = "https://gitlab.gnome.org/bilelmoussaoui/libadwaita-rs"
package = "libadwaita"
