name: flatpak

on: [push]

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        bundle: vaults.flatpak
        manifest-path: io.github.mpobaschnig.Vaults.Devel.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }}
